### ISSUE TITLE
/plot reset FATAL error

### ISSUE THREAD

**Issue by dongmin-dev** [tim03we/FuturePlots#24]
Using the latest FuturePlots.
When a user types /plot reset, the server crashes.

[FATAL] Exception happened while ticking server
java.lang.NoSuchMethodError: tim03we.futureplots.provider.DataProvider.isOwner(Ljava/lang/String;Ltim03we/futureplots/utils/Plot;)Z
        at tim03we.futureplots.utils.PlotPlayer.isOwner(PlotPlayer.java:38) ~[?:?]
        at tim03we.futureplots.utils.PlotPlayer.canByPass(PlotPlayer.java:42) ~[?:?]
        at tim03we.futureplots.utils.Plot.canByPass(Plot.java:71) ~[?:?]
        at tim03we.futureplots.commands.ClearCommand.execute(ClearCommand.java:38) ~[?:?]
        at tim03we.futureplots.commands.MainCommand.execute(MainCommand.java:47) ~[?:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:759) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2802) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_251]
        at cn.nukkit.network.Network.processPackets(Network.java:197) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:180) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2105) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:83) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:911) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:888) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:573) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]

**Comment by tim03we** [comment]
Make sure you are using the latest version (1.2.7.2-SNAPSHOT) Because the specified method in the message does not exist in the plugin and is not used anywhere. I just tested the plugin with the Nukkit build and the Github release and it worked fine.

**Comment by dongmin-dev** [comment]
I downloaded the plugin directly from your release.
I'll test some more and inform you

**Comment by dongmin-dev** [comment]
Solved!
Had the wrong Border manager 😂
