### ISSUE TITLE
Could not pass event "cn.nukkit.event.player.PlayerInteractEvent" to "FuturePlots v1.2.7.2": null on tim03we.futureplots.listener.PlayerInteract BUG.

### ISSUE THREAD

**Issue by SilentBlade1472** [tim03we/FuturePlots#25]
20:14:34 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerInteractEvent" to "FuturePlots v1.2.7.2": null on tim03we.futureplots.listener.PlayerInteract
20:14:34 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[server.jar:?]
at cn.nukkit.level.Level.useItemOn(Level.java:2052) ~[server.jar:?]
at cn.nukkit.level.Level.useItemOn(Level.java:2020) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:3038) ~[server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
at cn.nukkit.network.Network.processPackets(Network.java:197) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:180) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2105) [server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [server.jar:?]
at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [server.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [server.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:83) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1132) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:911) [server.jar:?]
at cn.nukkit.Server.start(Server.java:888) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:573) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.NullPointerException
at tim03we.futureplots.utils.Plot.canInteract(Plot.java:75) ~[?:?]
at tim03we.futureplots.listener.PlayerInteract.onInteract(PlayerInteract.java:25) ~[?:?]
at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
... 20 more
20:14:37 [INFO ] (**Entropy) (Phoenix) Silent: We also have these ranks.
20:14:39 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerInteractEvent" to "FuturePlots v1.2.7.2": null on tim03we.futureplots.listener.PlayerInteract
20:14:39 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[server.jar:?]
at cn.nukkit.level.Level.useItemOn(Level.java:2052) ~[server.jar:?]
at cn.nukkit.level.Level.useItemOn(Level.java:2020) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:3038) ~[server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
at cn.nukkit.network.Network.processPackets(Network.java:197) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:180) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2105) [server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [server.jar:?]
at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [server.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68) [server.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:83) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1132) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:911) [server.jar:?]
at cn.nukkit.Server.start(Server.java:888) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:573) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.NullPointerException
at tim03we.futureplots.utils.Plot.canInteract(Plot.java:75) ~[?:?]
at tim03we.futureplots.listener.PlayerInteract.onInteract(PlayerInteract.java:25) ~[?:?]
at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
... 20 more

**Comment by tim03we** [comment]
What exactly did you do to make this mistake?

**Comment by tim03we** [comment]
If your problem persists, please try the pre-release. 
https://github.com/tim03we/FuturePlots/releases/tag/1.2.7.3-SNAPSHOT

**Comment by SilentBlade1472** [comment]
I honestly don't know what caused It I just saw this error in console. I assume it was a conflict with GAC. But I'm not sure due to the lines at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
at cn.nukkit.network.Network.processPackets(Network.java:197) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:180) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2105) [server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]

But I will test if it's resolved in the pre-release.

**Comment by tim03we** [comment]
At first I also thought it was in conflict with GAC. But the developer of GAC thinks that it is not in conflict. Which I can't quite believe. Try the pre-release anyway. ;)

**Comment by SilentBlade1472** [comment]
I tried the prerelease and I haven't noticed it So far. But Since I'm op it's possible I'm exempt from the cheat detection. So I have to wait for a normal player to hop on later tonight to be positive before i can close the issue as solved.

**Comment by tim03we** [comment]
Okay.  Let's hope that was the problem.

**Comment by SilentBlade1472** [comment]
it wasn't. I saw a bunch of errors in console like this.

8:14:58 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:3115) ~[server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
at cn.nukkit.network.Network.processPackets(Network.java:197) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:180) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2105) [server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [server.jar:?]
at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [server.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [server.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:83) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1132) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:911) [server.jar:?]
at cn.nukkit.Server.start(Server.java:888) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:573) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.NullPointerException
at tim03we.futureplots.utils.Plot.canInteract(Plot.java:75) ~[?:?]
at tim03we.futureplots.listener.PlayerInteract.onInteract(PlayerInteract.java:30) ~[?:?]
at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
... 18 more
18:14:58 [FATAL] Could not pass event "cn.nukkit.event.block.BlockBreakEvent" to "FuturePlots v1.2.7.3": null on tim03we.futureplots.listener.BlockBreak
18:14:58 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[server.jar:?]
at cn.nukkit.level.Level.useBreakOn(Level.java:1920) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:3077) ~[server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
at cn.nukkit.network.Network.processPackets(Network.java:197) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:180) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2105) [server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [server.jar:?]
at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [server.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [server.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:83) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1132) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:911) [server.jar:?]
at cn.nukkit.Server.start(Server.java:888) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:573) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.NullPointerException
at tim03we.futureplots.utils.Plot.canInteract(Plot.java:75) ~[?:?]
at tim03we.futureplots.listener.BlockBreak.onBreak(BlockBreak.java:23) ~[?:?]
at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
... 19 more

and a player said plots are no longer protected. Im using the prerelease too.

**Comment by tim03we** [comment]
The funny thing is, the mistake doesn't show up in my life. Something's being done that makes the mistake.

**Comment by SilentBlade1472** [comment]
Is it possible that somehow GAC is conflicting? I could try disabling it and see if that resolves the problem tomorow?

**Comment by tim03we** [comment]
You can try it, yes.

**Comment by tim03we** [comment]
Since I haven't heard from you in over a week either, I assume that it works.
