### ISSUE TITLE
[Critical Bug] Players can break any unlocked plots again

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#27]
Same bug: #22

**Comment by GoodLucky777** [comment]
I think it is because #25

**Comment by tim03we** [comment]
If you also use the plugin GAC, try it without the plugin.

**Comment by GoodLucky777** [comment]
> If you also use the plugin GAC, try it without the plugin.

I don't have GAC

**Comment by tim03we** [comment]
I cannot reproduce the error, because the plugin works fine for me. Other branches like the Redstone branch, new-raknet branch are not supported from my side.

**Comment by GoodLucky777** [comment]
> I cannot reproduce the error, because the plugin works fine for me. Other branches like the Redstone branch, new-raknet branch are not supported from my side.

Error was:
```
2020-06-09 20:15:07.290 [main] FATAL - "cn.nukkit.event.block.BlockBreakEvent" event can't be pass to "FuturePlots v1.2.7.3": tim03we.futureplots.listener.BlockBreak null
2020-06-09 20:15:07.290 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.level.Level.useBreakOn(Level.java:1896) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:3084) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_252]
	at cn.nukkit.network.Network.processPackets(Network.java:196) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:181) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2105) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:84) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tick(Server.java:1140) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:919) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.start(Server.java:896) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:578) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
	at tim03we.futureplots.utils.Plot.canInteract(Plot.java:75) ~[?:?]
	at tim03we.futureplots.listener.BlockBreak.onBreak(BlockBreak.java:23) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
	... 17 more
```

**Comment by GoodLucky777** [comment]
also same in 1.2.7.2

**Comment by tim03we** [comment]
Try this file. 
https://workupload.com/file/EDUPM6Fzhhf

**Comment by tim03we** [comment]
Since I haven't heard anything for several days now whether it works or not, I assume that it works. So I will close this issue. I ask you not to create a new issue every time an issue already exists, just open it again.

**Comment by GoodLucky777** [comment]
Sorry for late reply, it is fixed. Thanks!
